on:
  push:
     branches:
       - master

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "car", "afex", "psych", "factoextra"))'

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
        
      - name: Push to GitHub Pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _book/*
          git commit -m "update book"
          git push origin gh-pages
        shell: bash

