on:
  push:
     branches:
       - master

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "car", "afex", "psych", "factoextra"), repos = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest")'

      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
        
      - name: Move files
        run: mv _book docs
        shell: bash

      - name: Push to GitHub Pages branch
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git fetch origin gh-pages
          git add --all .
          git commit -m "Built site for commit $GITHUB_SHA"
          # essentially what pkgdown does: https://github.com/r-lib/pkgdown/blob/9aae87398abdbe1cd5af5ff6f168d2e142d531c9/R/deploy-site.R#L193
          git push --force origin HEAD:gh-pages
        shell: bash
